apiVersion: v1
kind: ServiceAccount
metadata:
  name: ftptomongo-service-account  # Kubernetes service account name
imagePullSecrets:
  - name: ftptomongo-gcr-secret  # Optional: if you have a GCR secret
